### ISSUE TITLE
Mid Sprint Update 2019-02-11

### ISSUE THREAD

**Issue by kristoferbaxter** [kristoferbaxter/wg-performance#2]
## What Was Investigated?

How do we enforce AMP's UX no-content-jumping invariant in amp-script?

### Option A
If page receives mutation > X seconds after a gesture, terminate worker. Network responses triggered during gesture window will extend it, max 1 extension (e.g. to support amp-list use cases).

- Provides a clear performance budget for publishers. 
- Early termination is a clear signal for application developers, allowing more clear resolution to issues.
- Prevents a cascade of updates when a gesture allows for mutation.
- Avoids troubling DOM scenarios when the main thread and the worker thread have a different source of truth regarding structure. (ie `Element.classList.add('a')` is outside the mutation window how would the worker get a signal that the mutation was denied? The DOM APIs do not support negation or rollback semantics)

### Option B
If page receives mutation > X seconds after a gesture, store it in a queue. Dequeue on next user gesture. "Curtain" amp-script if queue gets old, terminate worker if queue gets too large.

- Far more forgiving for accidental changes outside mutation window.
- Simpler mental modal for document developers, a mutation requested will quite likely be made.
- Device performance isn't a factor in success of applying mutation.
- Allows for "pause and resume" semantics similar to light ads UX.

### Statically Sized `amp-script` Elements
Should we disable gesture constraint if amp-script is statically sized (similar to amp-iframe)?

**Comment by torch2424** [comment]
I like the idea of Option B. 

# User using AMP Document

Personally, I would rather have a page not jump, then jump after I've already given up on the action. There have been plenty of times when I realize, "welp, I guess thats broken", or I'll try to do something right before the jump, and then all of a sudden, it literally jumps under my finger. I think queuing them up will make the page feel broken / unresponsive, but not laggy and lead to mis-clicks.

I guess I'm in the UX perspective of, I'd rather it respond, or not respond at all.

# Publisher

I think this is much easier to understand, then to try to wrestle with this fetch request model of how much time you have to respond and things like that. Also, I feel like there is less room for abuse than option A. As the developer could just send of analytics pings on every gesture from within the worker to extend every single gesture if they would like. And for the idea of: "* Early termination is a clear signal for application developers, allowing more clear resolution to issues.", this could also be done with an error in the console for option B.

# AMP Developers

I feel like keeping track of the this timeout and monitoring what amp-script is doing is going to slow down the page (at least a little bit), and will be much harder to do / properly maintain. Also, I think a mutation queue is a good idea in general, the case of something rapidly mutating (like a game or animation), we can offer options in the future to drop mutations if another comes in.

**Comment by kristoferbaxter** [comment]
> I guess I'm in the UX perspective of, I'd rather it respond, or not respond at all.

I'm confused if this means you'd prefer future interactions to change more about the DOM in an `amp-script` or terminate the worker.

> "Early termination is a clear signal for application developers, allowing more clear resolution to issues.", this could also be done with an error in the console for option B.

A console error is pretty easy to miss unfortunately given the stream of errors in production documents. However, perhaps in development mode the `Worker` could terminate when exceeding the threshold... this might give some of the intended value.

> I feel like keeping track of the this timeout and monitoring what amp-script is doing is going to slow down the page (at least a little bit), and will be much harder to do / properly maintain.

The idea here is to mutate the prototype for `fetch` and `xhr` attaching additional data that is detectable by the mutation lifecycle in `WorkerDOM`. It's possible it will add some complexity, but I _believe_ this approach should work without impacting performance significantly.

> Also, I think a mutation queue is a good idea in general, the case of something rapidly mutating (like a game or animation), we can offer options in the future to drop mutations if another comes in.

I'd really like to avoid deduping mutations in runtime. This complexity would increase time for applying mutations and cause the code to be more complex to build and maintain.

**Comment by dreamofabear** [comment]
Another idea is to restructure this constraint around this idea:

> Should we disable gesture constraint if amp-script is statically sized (similar to amp-iframe)?

Always allow mutations from worker-dom but constrain resizing of `amp-script`. I.e. don't support `layout=container` and only supported fixed layout size, but automatically trigger resizes for `amp-script` after every mutation until X seconds after a user gesture.

**Comment by dreamofabear** [comment]
Aside: Should we migrate this to ampproject organization? Either use an existing WG or create `wg-performance`. /cc @mrjoro

**Comment by kristoferbaxter** [comment]
We have an outstanding request to the TSC to move this repo over to `@ampproject` under a new WG (wg-performance). See https://github.com/ampproject/meta/pull/23.

**Comment by kristoferbaxter** [comment]
@dvoytenko - for consideration in the implementation you're working on taking over.
